### ISSUE TITLE
Hexadecimal values support with \x escape

### ISSUE THREAD

**Issue by Vadimka29** [bazi/gsb4j#3]
https://github.com/bazi/gsb4j/blob/484645d4dbf680fb0bc1a752f0564e140bf7a5ab/core/src/test/java/kg/net/bazi/gsb4j/url/CanonicalizationTest.java#L91

Please suggest why did you comment this line? Yes, Java doesn't support '\x' escape symbol for hexadecimal values, but you still can replace all '\x' occurrences with '%' symbol manually and then you will be able to unescape every hexadecimal value prefixed with ''%".

The other problem here is that you will probably face 
`java.lang.IllegalArgumentException: java.text.ParseException: A prohibited code point was found in the input`
from java.net.IDN because of "�" uncoded symbol. This symbol is considered as "Prohibited"

Please take a look at line number 448 here:
http://cr.openjdk.java.net/~malenkov/8022746.8.0/jdk/src/share/classes/sun/net/idn/StringPrep.java-.html

Thanks!

**Comment by bazi** [comment]
Thanks @Vadimka29 for pointing out this issue. That line was commented out from the beginning because I could not find reasons why it was failing back then :)

After reading your post, I realized how simple the issue was and actually conversion was already done in the code [here](https://github.com/bazi/gsb4j/blob/c852ae1cdddc1852eee2e4fa0c38f14ead313360/core/src/main/java/kg/net/bazi/gsb4j/url/Canonicalization.java#L211). So after careful analysis I found that converting of '\x' to '%' was incorrectly performed before percent encoding [here](https://github.com/bazi/gsb4j/blob/c852ae1cdddc1852eee2e4fa0c38f14ead313360/core/src/main/java/kg/net/bazi/gsb4j/url/Canonicalization.java#L109). Moving conversion down below solved the issue and that test is passing now!

Good catch! Thanks again.
